version: "3.9"

services:

  app:
    image: laravel-app:local

    build: .

    container_name: laravel-app

    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - .:/var/www/html

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

  queue:
    image: laravel-app:local

    container_name: laravel-queue

    restart: unless-stopped

    command: php artisan queue:work --sleep=3 --tries=3 --timeout=300 --max-time=3600

    volumes:
      - .:/var/www/html

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

  schedule:
    image: laravel-app:local

    container_name: laravel-schedule

    restart: unless-stopped

    command: php artisan schedule:work

    volumes:
      - .:/var/www/html

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4

    container_name: laravel-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:
